-- db/seed.sql
-- GENERATED by scripts/crawl-catalog.ts — DO NOT EDIT BY HAND.
-- Regenerate with: bun run crawl:catalog
--
-- Point-in-time snapshot (2026-07-07T09:54:05.413Z) of the currently popular,
-- REAL provider / skill / mcp entries crawled from public sources:
--   provider → OpenRouter, skill → GitHub, mcp → PulseMCP.
-- Plus the 3 fixed TEST providers (local / yls / skyapi, tagged 'test').
-- Counts: mcp=10, provider=1, skill=10 (+3 test providers).

-- ── Publishers (test publishers + crawled) ──────────────────────────────────
INSERT INTO publishers (slug, name, avatar_url, tier, bio) VALUES
  ('agent-store', 'Agent Store', 'https://api.dicebear.com/9.x/shapes/svg?seed=agent-store', 'official', 'Agent Store 官方内置组件。'),
  ('yls-me', 'YLS.me', 'https://api.dicebear.com/9.x/shapes/svg?seed=yls', 'verified', '已验证的第三方模型接入服务。'),
  ('skyapi', 'SkyAPI', 'https://api.dicebear.com/9.x/shapes/svg?seed=skyapi', 'community', '稳定线路、免翻墙接入 Claude Code 的第三方接入服务。'),
  ('affaan-m', 'affaan-m', 'https://avatars.githubusercontent.com/u/124439313?v=4', 'community', NULL),
  ('agenttrust', 'agenttrust', 'https://github.com/agenttrust.png', 'community', NULL),
  ('ankimcp', 'ankimcp', 'https://github.com/ankimcp.png', 'community', NULL),
  ('anomalyarmor', 'anomalyarmor', 'https://github.com/anomalyarmor.png', 'community', NULL),
  ('anthropics', 'anthropics', 'https://avatars.githubusercontent.com/u/76263028?v=4', 'official', NULL),
  ('boolsai-ai', 'Boolsai-ai', 'https://github.com/Boolsai-ai.png', 'community', NULL),
  ('breverdbidder', 'breverdbidder', 'https://github.com/breverdbidder.png', 'community', NULL),
  ('community', 'Community', 'https://api.dicebear.com/9.x/shapes/svg?seed=community', 'community', NULL),
  ('dealfluence', 'dealfluence', 'https://github.com/dealfluence.png', 'community', NULL),
  ('frumu-ai', 'frumu-ai', 'https://github.com/frumu-ai.png', 'community', NULL),
  ('multica-ai', 'multica-ai', 'https://avatars.githubusercontent.com/u/254743058?v=4', 'community', NULL),
  ('obra', 'obra', 'https://avatars.githubusercontent.com/u/45416?v=4', 'community', NULL),
  ('openrouter', 'OpenRouter', 'https://api.dicebear.com/9.x/shapes/svg?seed=openrouter', 'official', '统一访问 300+ 模型的推理路由服务。'),
  ('techdocsstudio', 'TechDocsStudio', 'https://github.com/TechDocsStudio.png', 'community', NULL);

-- ── TEST providers (always present, real configs) ───────────────────────────
-- Provider: local (built-in relay) — the endpoint Claude/Codex point at; forwards
-- to upstream providers by level. No upstream API key. Rendered specially in the
-- CLI client (LOCAL_PROVIDER_SENTINEL __local__); this catalog row is its store listing.
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'local',
  'local',
  '内置本地转发：将 Claude Code / Codex 的 baseURL 指向本机监听端口，请求按 Level 优先级转发到已配置的上游供应商，失败自动降级。无需 API 密钥。',
  'provider', '1.0.0',
  (SELECT id FROM publishers WHERE slug = 'agent-store'),
  ARRAY['claude','codex'], ARRAY['relay','local','内置','test'], 0, 5.0, 'published',
  $${"steps":[]}$$,
  $${"configSchema":{},"supportedModels":[]}$$
);

-- Provider: yls (伊莉思 Code) — real China relay for Codex CLI. Pre-fills the codex
-- endpoint connection on install; user supplies the Bearer API key.
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'yls',
  'YLS Code',
  '伊莉思 Code 服务，国内直连免翻墙接入 Codex CLI（GPT-5 Code）与 Claude Code；此预设接入其 Codex 端点，按订阅计费。',
  'provider', '1.0.0',
  (SELECT id FROM publishers WHERE slug = 'yls-me'),
  ARRAY['codex'], ARRAY['relay','codex','国产','test'], 32000, 4.7, 'published',
  $${"steps":[{"type":"config","patch":{"apiKey":"","baseUrl":"https://code.ylsagi.com/codex","authType":"bearer","upstreamProtocol":"auto","level":1}}]}$$,
  $${"configSchema":{"type":"object","required":["apiKey"],"properties":{"apiKey":{"type":"string","description":"API 密钥 (Bearer)"},"baseUrl":{"type":"string","description":"API 地址","default":"https://code.ylsagi.com/codex"},"authType":{"type":"string","default":"bearer"},"upstreamProtocol":{"type":"string","default":"auto"},"level":{"type":"number","default":1}}},"supportedModels":["gpt-5-codex","gpt-5"]}$$
);

-- Provider: skyapi — real China relay for Claude Code (Anthropic protocol). Pre-fills
-- the claude endpoint connection on install; user supplies the x-api-key.
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'skyapi',
  'SkyAPI',
  'SkyAPI 服务，稳定线路免翻墙接入 Claude Code，兼容 Cursor / Cline / Windsurf 等客户端。',
  'provider', '1.0.0',
  (SELECT id FROM publishers WHERE slug = 'skyapi'),
  ARRAY['claude'], ARRAY['relay','claude','国产','test'], 21000, 4.5, 'published',
  $${"steps":[{"type":"config","patch":{"apiKey":"","baseUrl":"http://150.158.2.79:8888","authType":"anthropic","upstreamProtocol":"auto","level":1}}]}$$,
  $${"configSchema":{"type":"object","required":["apiKey"],"properties":{"apiKey":{"type":"string","description":"API 密钥 (x-api-key)"},"baseUrl":{"type":"string","description":"API 地址","default":"http://150.158.2.79:8888"},"authType":{"type":"string","default":"anthropic"},"upstreamProtocol":{"type":"string","default":"auto"},"level":{"type":"number","default":1}}},"supportedModels":["claude-opus-4-8","claude-sonnet-5","claude-haiku-4-5-20251001","claude-opus-4-5"]}$$
);

-- ── Crawled items (real, popularity-ranked) ─────────────────────────────────
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'ankimcp-anki-mcp-server', 'Anki MCP Server', 'MCP server for Anki flashcards: adaptive review, notes, media, and deck management via AnkiConnect.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'ankimcp'),
  ARRAY['claude','codex'], ARRAY['mcp','npm'], 370, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"stdio","serverCommand":"npx -y @ankimcp/anki-mcp-server","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'adeu-mcp-server', 'adeu', 'Automated DOCX Redlining Engine',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'dealfluence'),
  ARRAY['claude','codex'], ARRAY['mcp','npm'], 118, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"stdio","serverCommand":"npx -y @adeu/mcp-server","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'docs-mcp', 'docs-mcp', 'Remote MCP server for Tandem docs, install guides, SDKs, workflows, and agent setup help.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'frumu-ai'),
  ARRAY['claude','codex'], ARRAY['mcp','streamable-http'], 109, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"http","url":"https://tandem.ac/mcp","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'biel-ai', 'Biel.ai', 'Query your product docs from AI tools. Source-cited answers from your indexed documentation.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'techdocsstudio'),
  ARRAY['claude','codex'], ARRAY['mcp','streamable-http'], 3, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"http","url":"https://mcp.biel.ai/v2/{project_slug}/mcp","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'agenttrust-mcp-server', 'AgentTrust — Identity & Trust for A2A Agents', 'Identity, trust, and A2A orchestration for autonomous AI agents. Official A2A partner.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'agenttrust'),
  ARRAY['claude','codex'], ARRAY['mcp','npm'], 1, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"stdio","serverCommand":"npx -y @agenttrust/mcp-server","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'armor-mcp', 'AnomalyArmor', 'Data observability tools for engineering teams: alerts, freshness, schema drift, lineage, quality.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'anomalyarmor'),
  ARRAY['claude','codex'], ARRAY['mcp','streamable-http'], 1, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"http","url":"https://mcp.anomalyarmor.ai/mcp","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'biddeed-mcp', 'BidDeed MCP', 'AI-powered foreclosure auction intelligence for Florida counties via MCP tools.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'breverdbidder'),
  ARRAY['claude','codex'], ARRAY['mcp','streamable-http'], 1, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"http","url":"https://mcp.biddeed.ai/api/mcp","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'directory', 'Boolsai Directory', 'Indexed ecommerce site directory — vendor lookups, brands by city/market/founder. 10 tools.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'boolsai-ai'),
  ARRAY['claude','codex'], ARRAY['mcp','streamable-http'], 1, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"http","url":"https://directory.boolsai.ai/mcp","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'grep', 'Boolsai Grep', 'Parallel regex across all Boolsai scans — discover new vendor patterns, niche signals. 4 tools.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'boolsai-ai'),
  ARRAY['claude','codex'], ARRAY['mcp','streamable-http'], 1, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"http","url":"https://grep.boolsai.ai/mcp","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'mcp', 'inference.sh', 'Run 150+ AI apps — image, video, audio, LLMs, 3D and more. Browse, execute, stream results.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'community'),
  ARRAY['claude','codex'], ARRAY['mcp','streamable-http'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"http","url":"https://sh.inference.ac","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'openrouter', 'OpenRouter', 'OpenRouter：一个 API Key 访问 300+ 模型（OpenAI 兼容）。此预设已填好接入地址，你只需填入自己的 OpenRouter API Key。',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'openrouter'),
  ARRAY['codex'], ARRAY['provider'], 0, 0, 'published',
  '{"steps":[{"type":"config","patch":{"apiKey":"","baseUrl":"https://openrouter.ai/api/v1","authType":"bearer","endpointPath":"/chat/completions","upstreamProtocol":"auto","level":1}}]}'::jsonb, '{"configSchema":{"type":"object","required":["apiKey"],"properties":{"apiKey":{"type":"string","description":"OpenRouter API Key (Bearer)"},"baseUrl":{"type":"string","description":"API 地址","default":"https://openrouter.ai/api/v1"},"authType":{"type":"string","default":"bearer"},"level":{"type":"number","default":1}}},"supportedModels":["tencent/hy3:free","tencent/hy3","poolside/laguna-xs-2.1:free","poolside/laguna-xs-2.1","anthropic/claude-sonnet-5","google/gemini-3.1-flash-lite-image","nex-agi/nex-n2-mini","sakana/fugu-ultra","google/gemini-3.1-flash-image","google/gemini-3-pro-image","cohere/north-mini-code:free","z-ai/glm-5.2","openrouter/fusion","moonshotai/kimi-k2.7-code","~anthropic/claude-fable-latest","anthropic/claude-fable-5","nex-agi/nex-n2-pro","nvidia/nemotron-3.5-content-safety:free","nvidia/nemotron-3-ultra-550b-a55b:free","nvidia/nemotron-3-ultra-550b-a55b"]}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'superpowers-brainstorming', 'brainstorming', 'You MUST use this before any creative work - creating features, building components, adding functionality, or modifying behavior. Explores user intent, requirements and design before implementation.',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'obra'),
  ARRAY['claude'], ARRAY['skill'], 248198, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/obra/superpowers/main/skills/brainstorming/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/obra/superpowers/main/skills/brainstorming/SKILL.md","source":{"repo":"obra/superpowers","ref":"main","path":"skills/brainstorming/SKILL.md"}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'superpowers-dispatching-parallel-agents', 'dispatching-parallel-agents', 'Use when facing 2+ independent tasks that can be worked on without shared state or sequential dependencies',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'obra'),
  ARRAY['claude'], ARRAY['skill'], 248198, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/obra/superpowers/main/skills/dispatching-parallel-agents/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/obra/superpowers/main/skills/dispatching-parallel-agents/SKILL.md","source":{"repo":"obra/superpowers","ref":"main","path":"skills/dispatching-parallel-agents/SKILL.md"}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'superpowers-executing-plans', 'executing-plans', 'Use when you have a written implementation plan to execute in a separate session with review checkpoints',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'obra'),
  ARRAY['claude'], ARRAY['skill'], 248198, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/obra/superpowers/main/skills/executing-plans/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/obra/superpowers/main/skills/executing-plans/SKILL.md","source":{"repo":"obra/superpowers","ref":"main","path":"skills/executing-plans/SKILL.md"}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'ecc-agent-introspection-debugging', 'agent-introspection-debugging', 'Structured self-debugging workflow for AI agent failures using capture, diagnosis, contained recovery, and introspection reports.',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'affaan-m'),
  ARRAY['claude'], ARRAY['skill'], 226809, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/agent-introspection-debugging/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/agent-introspection-debugging/SKILL.md","source":{"repo":"affaan-m/ECC","ref":"main","path":".agents/skills/agent-introspection-debugging/SKILL.md"}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'ecc-agent-sort', 'agent-sort', 'Build an evidence-backed ECC install plan for a specific repo by sorting skills, commands, rules, hooks, and extras into DAILY vs LIBRARY buckets using parallel repo-aware review passes. Use when ECC should be trimmed to what a project actually needs instead of loading the full bundle.',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'affaan-m'),
  ARRAY['claude'], ARRAY['skill'], 226809, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/agent-sort/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/agent-sort/SKILL.md","source":{"repo":"affaan-m/ECC","ref":"main","path":".agents/skills/agent-sort/SKILL.md"}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'ecc-api-design', 'api-design', 'REST API design patterns including resource naming, status codes, pagination, filtering, error responses, versioning, and rate limiting for production APIs.',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'affaan-m'),
  ARRAY['claude'], ARRAY['skill'], 226809, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/api-design/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/api-design/SKILL.md","source":{"repo":"affaan-m/ECC","ref":"main","path":".agents/skills/api-design/SKILL.md"}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'andrej-karpathy-skills-karpathy-guidelines', 'karpathy-guidelines', 'Behavioral guidelines to reduce common LLM coding mistakes. Use when writing, reviewing, or refactoring code to avoid overcomplication, make surgical changes, surface assumptions, and define verifiable success criteria.',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'multica-ai'),
  ARRAY['claude'], ARRAY['skill'], 188801, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/multica-ai/andrej-karpathy-skills/main/skills/karpathy-guidelines/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/multica-ai/andrej-karpathy-skills/main/skills/karpathy-guidelines/SKILL.md","source":{"repo":"multica-ai/andrej-karpathy-skills","ref":"main","path":"skills/karpathy-guidelines/SKILL.md"}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'skills-algorithmic-art', 'algorithmic-art', 'Creating algorithmic art using p5.js with seeded randomness and interactive parameter exploration. Use this when users request creating art using code, generative art, algorithmic art, flow fields, or particle systems. Create original algorithmic art rather than copying existing artists'' work to avo',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'anthropics'),
  ARRAY['claude'], ARRAY['skill'], 159019, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/anthropics/skills/main/skills/algorithmic-art/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/anthropics/skills/main/skills/algorithmic-art/SKILL.md","source":{"repo":"anthropics/skills","ref":"main","path":"skills/algorithmic-art/SKILL.md"}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'skills-brand-guidelines', 'brand-guidelines', 'Applies Anthropic''s official brand colors and typography to any sort of artifact that may benefit from having Anthropic''s look-and-feel. Use it when brand colors or style guidelines, visual formatting, or company design standards apply.',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'anthropics'),
  ARRAY['claude'], ARRAY['skill'], 159019, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/anthropics/skills/main/skills/brand-guidelines/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/anthropics/skills/main/skills/brand-guidelines/SKILL.md","source":{"repo":"anthropics/skills","ref":"main","path":"skills/brand-guidelines/SKILL.md"}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'skills-canvas-design', 'canvas-design', 'Create beautiful visual art in .png and .pdf documents using design philosophy. You should use this skill when the user asks to create a poster, piece of art, design, or other static piece. Create original visual designs, never copying existing artists'' work to avoid copyright violations.',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'anthropics'),
  ARRAY['claude'], ARRAY['skill'], 159019, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/anthropics/skills/main/skills/canvas-design/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/anthropics/skills/main/skills/canvas-design/SKILL.md","source":{"repo":"anthropics/skills","ref":"main","path":"skills/canvas-design/SKILL.md"}}'::jsonb
);

